PKGDIR  ?= ../..
L4DIR   ?= $(PKGDIR)/../../..

TARGET      = libc_be_sig_noop.a libc_be_sig_noop.so
PC_FILENAME = libc_be_sig_noop
SRC_CC      = sig.cc
CXXFLAGS        = -fno-exceptions

include $(L4DIR)/mk/lib.mk
