PKGDIR ?= ../..
L4DIR  ?= $(PKGDIR)/../../..

TARGET	      = lib4re-c-util.a lib4re-c-util.so
SRC_CC       := cap_alloc.cc video/goos_fb.cc kumem_alloc.cc
PC_FILENAME   = l4re_c-util
REQUIRES_LIBS = l4re_c l4re-util

include $(L4DIR)/mk/lib.mk
