# Makefile for uClibc
#
# Copyright (C) 2008 Paul Mundt <lethal@linux-sh.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC-y := __init_brk.c brk.c sbrk.c syscall.c

SSRC-y := setjmp.S __longjmp.S
