# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC-y := bsd-setjmp.c bsd-_setjmp.c

SSRC-y := __longjmp.S setjmp.S
