PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../../..

TARGET        = ned-prompt
SRC_CC        = ned-prompt.cc
REQUIRES_LIBS = readline libc_be_file_stdin
DEPENDS_PKG   = readline

include $(L4DIR)/mk/prog.mk
