PKGDIR          ?= ../..
L4DIR           ?= $(PKGDIR)/../../..

TARGET        = ned-prompt
SRC_CC        = ned-prompt.cc
REQUIRES_LIBS := readline
DEPENDS_PKGS  := readline

include $(L4DIR)/mk/prog.mk
