PKGDIR		?= ../../..
L4DIR		?= $(PKGDIR)/../../..

TARGET		= libcxx_io_kdebug
PC_FILENAME     = cxx_io_kdebug
SRC_CC		= iostream.cc

CXX_PKG_DIR=$(PKGDIR)
include $(PKGDIR)/lib/Makefile.inc
include $(L4DIR)/mk/lib.mk

$(GENERAL_D_LOC): $(CXX_PKG_DIR)/lib/Makefile.inc
