PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../../..
PKGNAME := re
EXTRA_TARGET += \
  cap_alloc \
  console   \
  consts    \
  dataspace \
  debug     \
  dma_space \
  env       \
  error_helper \
  event     \
  log       \
  inhibitor \
  mem_alloc \
  mmio_space \
  namespace \
  parent    \
  rm        \
  unique_cap \
  video/colors \
  video/goos \
  video/view

include $(L4DIR)/mk/include.mk
