PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../../..

TARGET		= libmount.a libmount.so
LINK_INCR       = libmount.a
PC_FILENAME     = libmount
SRC_CC          = mount.cc
CXXFLAGS        = -fno-exceptions

include $(L4DIR)/mk/lib.mk
