# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC-y := __syscall_error.c ioctl.c

SSRC-y := \
	__longjmp.S setjmp.S bsd-setjmp.S bsd-_setjmp.S brk.S \
	__uClibc_syscall.S syscall.S

SSRC-$(if $(UCLIBC_HAS_THREADS_NATIVE),,y) += clone.S vfork.S

ifeq ($(CONFIG_E500),y)
ARCH_HEADERS := fenv.h
endif
