PKGDIR     ?= ../..
L4DIR      ?= $(PKGDIR)/../../..

TARGET      = libc_be_socket_noop.a libc_be_socket_noop.so
PC_FILENAME = libc_be_socket_noop
SRC_C       = socket_noop.c

include $(L4DIR)/mk/lib.mk
