PKGDIR = ../..
L4DIR ?= $(PKGDIR)/../..

TEST_GROUP    := l4re-core/libc_be_minimal_io

REQUIRES_LIBS := cxx_io cxx_libc_io libc_be_minimal_log_io
DEPENDS_PKGS  := atkins

include $(L4DIR)/mk/test.mk
