# Makefile for uClibc NPTL
#
# Copyright (C) 2006 Steven J. Hill <sjhill@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

libpthread_linux_arch_SSRC = pt-vfork.S clone.S pthread_spin_unlock.S pthread_once.S
libpthread_linux_arch_CSRC = pthread_spin_init.c pt-__syscall_error.c

libc_linux_arch_CSRC = fork.c
libc_linux_arch_SSRC = clone.S vfork.S

ASFLAGS += -DUSE___THREAD

