# Makefile for uClibc NPTL
#
# Copyright (C) 2006 Steven J. Hill <sjhill@uclibc.org>
#
# Licensed under the LGPL v2.1 or later, see the file COPYING.LIB in this tarball.
#

libpthread_linux_arch_SSRC = pt-vfork.S
libpthread_linux_arch_CSRC = pthread_once.c \
	pt-__syscall_rt_sigaction.c pt-__syscall_error.c \
	lowlevellock.c

libc_linux_arch_CSRC = fork.c libc-lowlevellock.c
libc_linux_arch_SSRC = clone.S vfork.S
libc_linux_arch_SSRC-OMIT = waitpid.S

CFLAGS += $(SSP_ALL_CFLAGS)

