PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../../..

TARGET		= libinitcwd.a libinitcwd.so
LINK_INCR       = libinitcwd.a
PC_FILENAME     = libinitcwd
SRC_CC          = initcwd.cc
CXXFLAGS        = -fno-exceptions

include $(L4DIR)/mk/lib.mk
