# Makefile for uClibc NPTL
#
# Copyright (C) 2009 Bernhard Reutner-Fischer <uclibc@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

libpthread_linux_arch_SSRC = pt-vfork.S
libpthread_linux_arch_CSRC = pthread_once.c pt-__syscall_error.c

libc_linux_arch_CSRC = fork.c
libc_linux_arch_SSRC = clone.S vfork.S

# powerpc32's PSEUDO_RET needs __syscall_error@local
librt_linux_arch_CSRC = pt-__syscall_error.c

ASFLAGS += -DUSE___THREAD

