PKGDIR	= ../../..
L4DIR	?= $(PKGDIR)/../../..
EXTRA_TARGET := \
  arith       \
  auto_ptr    \
  avl_tree    \
  avl_set     \
  avl_map     \
  bitmap      \
  dlist       \
  hlist       \
  slist       \
  list        \
  list_alloc  \
  minmax      \
  observer    \
  pair        \
  ref_ptr     \
  slab_alloc  \
  static_container \
  std_alloc   \
  std_ops     \
  type_traits \
  type_list \
  bitfield \
  unique_ptr \
  utils       \
  weak_ref

include $(L4DIR)/mk/include.mk
