/* vi: set sw=4 ts=4: */
/* Xtensa ELF shared library loader suppport
 *
 * Copyright (C) 2007 Tensilica Inc.
 *
 * Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
 */

static const char * const _dl_reltypes_tab[] =
{
	 [0] "R_XTENSA_NONE",			"R_XTENSA_32",
	 [2] "R_XTENSA_RTLD",			"R_XTENSA_GLOB_DAT",
	 [4] "R_XTENSA_JMP_SLOT",		"R_XTENSA_RELATIVE",
	 [6] "R_XTENSA_PLT",			"R_XTENSA_UNUSED7",
	 [8] "R_XTENSA_OP0",			"R_XTENSA_OP1",
	[10] "R_XTENSA_OP2",			"R_XTENSA_ASM_EXPAND",
	[12] "R_XTENSA_ASM_SIMPLIFY",	"R_XTENSA_UNUSED13",
	[14] "R_XTENSA_UNUSED14",		"R_XTENSA_GNU_VTINHERIT",
	[16] "R_XTENSA_GNU_VTENTRY",	"R_XTENSA_DIFF8",
	[18] "R_XTENSA_DIFF16",			"R_XTENSA_DIFF32",
	[20] "R_XTENSA_SLOT0_OP",		"R_XTENSA_SLOT1_OP",
	[22] "R_XTENSA_SLOT2_OP",		"R_XTENSA_SLOT3_OP",
	[24] "R_XTENSA_SLOT4_OP",		"R_XTENSA_SLOT5_OP",
	[26] "R_XTENSA_SLOT6_OP",		"R_XTENSA_SLOT7_OP",
	[28] "R_XTENSA_SLOT8_OP",		"R_XTENSA_SLOT9_OP",
	[30] "R_XTENSA_SLOT10_OP",		"R_XTENSA_SLOT11_OP",
	[32] "R_XTENSA_SLOT12_OP",		"R_XTENSA_SLOT13_OP",
	[34] "R_XTENSA_SLOT14_OP",		"R_XTENSA_SLOT0_ALT",
	[36] "R_XTENSA_SLOT1_ALT",		"R_XTENSA_SLOT2_ALT",
	[38] "R_XTENSA_SLOT3_ALT",		"R_XTENSA_SLOT4_ALT",
	[40] "R_XTENSA_SLOT5_ALT",		"R_XTENSA_SLOT6_ALT",
	[42] "R_XTENSA_SLOT7_ALT",		"R_XTENSA_SLOT8_ALT",
	[44] "R_XTENSA_SLOT9_ALT",		"R_XTENSA_SLOT10_ALT",
	[46] "R_XTENSA_SLOT11_ALT",		"R_XTENSA_SLOT12_ALT",
	[48] "R_XTENSA_SLOT13_ALT",		"R_XTENSA_SLOT14_ALT",
	[50] "R_XTENSA_TLSDESC_FN",		"R_XTENSA_TLSDESC_ARG",
	[52] "R_XTENSA_TLS_TPOFF"
};
