PKGDIR	?= ../..
L4DIR	?= $(PKGDIR)/../../..
PKGNAME := re/util
EXTRA_TARGET +=      \
  bitmap_cap_alloc   \
  br_manager         \
  cap                \
  cap_alloc          \
  counting_cap_alloc \
  dataspace_svr      \
  debug              \
  env_ns             \
  event_buffer       \
  event_svr          \
  icu_svr            \
  item_alloc         \
  meta               \
  name_space_svr     \
  object_registry    \
  poll_timeout_kipclock \
  region_mapping     \
  region_mapping_svr \
  region_mapping_svr_2 \
  vcon_svr           \
  video/goos_svr     \
  video/goos_fb      \
  event              \
  kumem_alloc


include $(L4DIR)/mk/include.mk
